content: |-
  # Terraform Module: Cloud Access for Wayfinder on AWS

  This Terraform Module can be used to provision IAM Roles that Wayfinder assumes into, for creating resources within an AWS Account (VPC, EKS Cluster, Route53 DNS Zones, etc).

  **Notes:**
  * The IAM Role ARN (`var.wayfinder_iam_role_arn`) used by Wayfinder (via IAM Roles for Service Accounts) must be provided to update the IAM Role Trust Policy for any Roles created by this module.
  * The `var.instance_id` is optional for reference to the Wayfinder instance, if you are using multiple Wayfinder instances in the same AWS account.
  * The `var.workspace_id` is optional for reference to a Wayfinder workspace. This may be relevant if the same AWS Account is linked to multiple workspaces, and you want to attribute any Cloud actions to a specific workspace.

  ## Deployment

  Please see the [examples](./examples) directory to see how to deploy this module.

  ## Updating Docs

  The `terraform-docs` utility is used to generate this README. Follow the below steps to update:
  1. Make changes to the `.terraform-docs.yml` file
  2. Fetch the `terraform-docs` binary (https://terraform-docs.io/user-guide/installation/)
  3. Run `terraform-docs markdown table --output-file ${PWD}/README.md --output-mode inject .`

  {{ .Inputs }}

  {{ .Outputs }}
