name: Terraform
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    - vnext

permissions:
  contents: read
  pull-requests: write

jobs:
  root-module-validation:
    uses: appvia/appvia-cicd-workflows/.github/workflows/terraform-module-validation.yml@composite-actions
    name: Root Module Validation

  cloudaccess-module-validation:
    uses: appvia/appvia-cicd-workflows/.github/workflows/terraform-module-validation.yml@composite-actions
    name: Cloud Access Module Validation
    with:
      working-directory: modules/cloudaccess
